version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1115
    ports:
      - 5432:5432
    networks:
      - default
      - database

networks:
  database:
    driver: bridge
